Repository eldolar/api, pull requests merged in 2020-10, with the labels that each got.

#10 Add common contributing file
  CONTRIBUTING.md
Labels: Hacktoberfest

#16 Update README.md
  README.md
Labels: hacktoberfest-accepted

#20 Add the urls of the homebankings, and add url at schema
  src/models/exchange.ts
  src/routers/exchangeRouter.ts
  src/services/bankInterfaces.ts
  src/services/fetchers/bancor.ts
  src/services/fetchers/bbva.ts
  src/services/fetchers/galicia.ts
  src/services/fetchers/icbc.ts
  src/services/fetchers/nacion.ts
  src/services/fetchers/santander.ts
  src/services/fetchers/supervielle.ts
  test/services/fetchers/bancor.spect.ts
  test/services/fetchers/bbva.spec.ts
  test/services/fetchers/galicia.spec.ts
  test/services/fetchers/icbc.spec.ts
  test/services/fetchers/nacion.spec.ts
  test/services/fetchers/santander.spect.ts
  test/services/fetchers/supervielle.spec.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#21 Bancor URL fixed and SSL Certified ignored for Bancor API
  src/services/fetchers/bancor.ts
Labels: Hacktoberfest, hacktoberfest-accepted
